In [11]:
from turtle import width
from click import style
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import os
import plotly.graph_objects as go
from pathlib import Path
import sys
import random
import plotly.express as px
import tensorflow as tf
import keras
from keras.datasets import mnist
import numpy as np
import pandas as pd
#import random
import time
from sktime.classification.interval_based import RandomIntervalSpectralEnsemble
from sktime.classification.dictionary_based import ContractableBOSS, BOSSEnsemble 
from sktime.datatypes._panel._convert import from_2d_array_to_nested
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import RidgeClassifierCV
from sktime.transformations.panel.rocket import Rocket
from wildboar.datasets import list_datasets, load_dataset
from wildboar.ensemble import ShapeletForestClassifier
# import pywt
# from pywt import wavedec, waverec
from tqdm import tqdm
import pickle
from tslearn.clustering import TimeSeriesKMeans
from sklearn.cluster import KMeans
from tslearn.generators import random_walks
# from extremum_config import app
# THIS_FILEPATH = os.path.dirname(__file__)
# sys.path.append(os.path.join(THIS_FILEPATH, "/Users/djedjakamara/Desktop/Internship/RISE/extreme-master/EXTREMUM/extremum_config.py"))


In [22]:
x_all, y_all = load_dataset("BME", repository='wildboar/ucr')
x_all

array([[0.03776463, 0.00025311, 0.00397708, ..., 0.03152316, 0.03978737,
        0.0206608 ],
       [0.00042488, 0.02098182, 0.00252583, ..., 0.00778903, 0.0291942 ,
        0.02183739],
       [0.01985576, 0.00367659, 0.03507744, ..., 0.02247886, 0.03220358,
        0.04518721],
       ...,
       [0.02997444, 0.04949607, 0.03869945, ..., 0.05944266, 0.05236799,
        0.05158482],
       [0.0207264 , 0.01333661, 0.00247677, ..., 0.01769541, 0.02562373,
        0.03158557],
       [0.04917323, 0.02625857, 0.03536249, ..., 0.02301583, 0.03186432,
        0.02313159]])

In [5]:
df = pd.DataFrame(x_all, y_all)
# df.reset_index(drop=False, inplace=True)
df3 = df.transpose
df3

<bound method DataFrame.transpose of           0         1         2         3         4         5         6    \
1.0 -0.335032 -0.335032 -0.335032 -0.335032 -0.335032 -0.335032 -0.335032   
1.0 -0.602525 -0.602525 -0.602525 -0.602525 -0.602525 -0.602525 -0.602525   
1.0 -0.320222 -0.320222 -0.320222 -0.320222 -0.320222 -0.320222 -0.320222   
1.0 -0.212916 -0.212916 -0.212916 -0.212916 -0.212916 -0.212916 -0.212916   
1.0 -0.185805 -0.185805 -0.185805 -0.185805 -0.185805 -0.185805 -0.185805   
..        ...       ...       ...       ...       ...       ...       ...   
2.0 -0.493855 -0.493855 -0.493855 -0.493855 -0.493855 -0.493855 -0.493855   
2.0  1.533909 -0.440701 -0.744487 -0.744487 -0.744487 -0.744487 -0.744487   
2.0 -0.370829 -0.370829 -0.370829 -0.370829 -0.370829 -0.370829 -0.370829   
2.0  1.648930  1.175427  1.648930  1.175427  1.175427  1.648930  1.175427   
2.0 -0.431681 -0.431681 -0.431681 -0.431681 -0.431681 -0.431681 -0.431681   

          7         8         9    ...

In [93]:
df2 = df.set_index('index', 1, inplace=True)


/Users/djedjakamara/opt/anaconda3/envs/extremum/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.set_index except for the argument 'keys' will be keyword-only
  """Entry point for launching an IPython kernel.


KeyError: "None of ['index'] are in the columns"

[array([[0.03776463, 0.00025311, 0.00397708, ..., 0.03152316, 0.03978737,
         0.0206608 ],
        [0.00042488, 0.02098182, 0.00252583, ..., 0.00778903, 0.0291942 ,
         0.02183739],
        [0.01985576, 0.00367659, 0.03507744, ..., 0.02247886, 0.03220358,
         0.04518721],
        ...,
        [0.02997444, 0.04949607, 0.03869945, ..., 0.05944266, 0.05236799,
         0.05158482],
        [0.0207264 , 0.01333661, 0.00247677, ..., 0.01769541, 0.02562373,
         0.03158557],
        [0.04917323, 0.02625857, 0.03536249, ..., 0.02301583, 0.03186432,
         0.02313159]]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2

In [56]:
pd.options.plotting.backend = "plotly"
df = pd.DataFrame(x_all, y_all)
# df.plot(x=np.arange(0, float(x_all.shape[1]), 1), y=x_all)
np.arange(0, float(x_all.shape[1]), 1) 
x_all[0]

array([-0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33503181,
       -0.33503181, -0.33503181, -0.33503181, -0.33503181, -0.33

In [4]:
UCR_datasets = list_datasets(repository='wildboar/ucr')

dataset_info = pd.DataFrame(columns=['size', 'classes', 'length'], index = UCR_datasets, dtype=float)
dataset_info

size  classes  length
ACSF1                NaN      NaN     NaN
Adiac                NaN      NaN     NaN
AllGestureWiimoteX   NaN      NaN     NaN
AllGestureWiimoteY   NaN      NaN     NaN
AllGestureWiimoteZ   NaN      NaN     NaN
...                  ...      ...     ...
Wine                 NaN      NaN     NaN
WordSynonyms         NaN      NaN     NaN
Worms                NaN      NaN     NaN
WormsTwoClass        NaN      NaN     NaN
Yoga                 NaN      NaN     NaN

[128 rows x 3 columns]

In [5]:
from tslearn.generators import random_walks
X = random_walks(n_ts=50, sz=32, d=1)
km = TimeSeriesKMeans(n_clusters=3, metric="euclidean", max_iter=5, random_state=0).fit(X)
km.cluster_centers_

array([[[ 0.48358785],
        [ 0.56517155],
        [ 0.79176754],
        [ 1.31029502],
        [ 1.47422719],
        [ 1.1902202 ],
        [ 1.70552119],
        [ 2.03190022],
        [ 2.0905088 ],
        [ 2.44665042],
        [ 2.55471679],
        [ 2.5472739 ],
        [ 2.80057358],
        [ 3.40121677],
        [ 3.89064034],
        [ 3.84071958],
        [ 3.87708737],
        [ 4.34730084],
        [ 4.34243867],
        [ 4.56028681],
        [ 4.34560387],
        [ 4.72446587],
        [ 4.85696313],
        [ 5.3302764 ],
        [ 5.60650229],
        [ 5.86443756],
        [ 5.64386151],
        [ 5.66045722],
        [ 5.67639788],
        [ 5.57241332],
        [ 5.45367375],
        [ 5.81868479]],

       [[-0.06989768],
        [ 0.21509684],
        [ 0.0800721 ],
        [ 0.30018676],
        [ 0.02106128],
        [-0.10097227],
        [-0.24801376],
        [-0.37440441],
        [-0.48954313],
        [-0.9725725 ],
        [-1.30006268],
        [

In [6]:
x_all, y_all = load_dataset(dataset, repository='wildboar/ucr')
timeseries = []
for i in range(0, len(x_all)):   
    if y_all[i] in classes: 
        timeseries.append(x_all[i])
X = timeseries
km = TimeSeriesKMeans(n_clusters=2, metric="euclidean", random_state=0).fit(X)
km.cluster_centers_
for centroid in km.cluster_centers_:
    print(centroid)

NameError: name 'dataset' is not defined

In [112]:
x_all

array([[-0.33503181, -0.33503181, -0.33503181, ..., -0.33503181,
        -0.33503181, -0.33503181],
       [-0.60252494, -0.60252494, -0.60252494, ..., -0.60252494,
        -0.60252494, -0.60252494],
       [-0.32022151, -0.32022151, -0.32022151, ..., -0.32022151,
        -0.32022151, -0.32022151],
       ...,
       [-0.37082887, -0.37082887, -0.37082887, ..., -0.37082887,
        -0.37082887, -0.37082887],
       [ 1.6489296 ,  1.17542684,  1.6489296 , ..., -0.7185843 ,
        -0.7185843 , -0.7185843 ],
       [-0.43168071, -0.43168071, -0.43168071, ...,  1.89997804,
         1.89997804,  1.89997804]])

In [21]:
classes = [1]
data = []
for j in range(0, len(classes)):
    current = classes[j]
    for i in range(0, len(x_all)):   
        if y_all[i] == current:       
            data.append(x_all[i])
km = TimeSeriesKMeans(n_clusters=2, metric="euclidean", random_state=0).fit(data)
centroids = km.cluster_centers_
centroids[0]

array([[-3.31202797e-01],
       [-3.35686172e-01],
       [-3.95332266e-01],
       [-3.86736991e-01],
       [-4.57034778e-01],
       [-4.11464298e-01],
       [-4.34050453e-01],
       [-4.62492742e-01],
       [-4.45255088e-01],
       [-4.92730553e-01],
       [-4.76029020e-01],
       [-4.95535987e-01],
       [-4.92661708e-01],
       [-5.21688952e-01],
       [-5.50563742e-01],
       [-5.21620554e-01],
       [-5.43570191e-01],
       [-5.25633898e-01],
       [-5.14261529e-01],
       [-5.65354100e-01],
       [-5.19933303e-01],
       [-5.40941603e-01],
       [-4.97746795e-01],
       [-5.33216766e-01],
       [-5.88642021e-01],
       [-5.53767491e-01],
       [-5.83141702e-01],
       [-5.59977094e-01],
       [-5.75796255e-01],
       [-5.92002291e-01],
       [-5.81208691e-01],
       [-5.80825727e-01],
       [-5.82396565e-01],
       [-5.81300192e-01],
       [-5.84647863e-01],
       [-5.80945744e-01],
       [-5.82292686e-01],
       [-5.89328279e-01],
       [-5.6

In [117]:
x_all

array([[-0.33503181, -0.33503181, -0.33503181, ..., -0.33503181,
        -0.33503181, -0.33503181],
       [-0.60252494, -0.60252494, -0.60252494, ..., -0.60252494,
        -0.60252494, -0.60252494],
       [-0.32022151, -0.32022151, -0.32022151, ..., -0.32022151,
        -0.32022151, -0.32022151],
       ...,
       [-0.37082887, -0.37082887, -0.37082887, ..., -0.37082887,
        -0.37082887, -0.37082887],
       [ 1.6489296 ,  1.17542684,  1.6489296 , ..., -0.7185843 ,
        -0.7185843 , -0.7185843 ],
       [-0.43168071, -0.43168071, -0.43168071, ...,  1.89997804,
         1.89997804,  1.89997804]])

In [14]:
# arr = {}
# for i in range(0, len(x_all)):
#     if  not int(y_all[i]) in arr.keys():
#         arr[int(y_all[i])] = []
#     if y_all[i] in classes: 
#         arr[int(y_all[i])].append(x)

# arr

dict2 = {}
for y, x in zip(y_all, x_all):
   if  not int(y_all[int(y)]) in list(dict2.keys()):
        dict2[y] = [] 
   dict2[y].append(x)

dict2

KeyError: 2.0

In [6]:
import numpy as np
r = np.fft.rfft(x_all)
amplitude = np.absolute(r)
phase = np.angle(x_all)

array([[4.94718552e-06, 2.37230198e+02, 2.26299246e+02, ...,
        5.09453748e+00, 5.02182699e+00, 5.29401428e+00],
       [6.67572021e-06, 2.23856991e+02, 2.33634907e+02, ...,
        7.61455318e+00, 6.18541746e+00, 4.60058355e+00],
       [1.03730708e-05, 7.18472440e+01, 2.21007161e+02, ...,
        3.51157257e-01, 5.56674784e-01, 2.33833598e-01],
       ...,
       [3.05473804e-06, 1.75941559e+02, 1.98977098e+01, ...,
        3.88331746e+00, 4.80636757e+00, 4.09504223e+00],
       [1.12503767e-05, 4.12523000e+02, 1.77092585e+02, ...,
        5.63810019e+00, 4.48749979e+00, 2.84101646e+00],
       [2.55182385e-06, 1.29113033e+02, 2.31933710e+02, ...,
        2.71926241e+00, 5.26472082e-01, 4.89648405e+00]])

In [52]:
nb_clusters = 4

x = np.arange(1, x_all.shape[1]+1)
data = []
classes=[1,2]
for j in range(0, len(classes)):
    current = classes[j]
    for i in range(0, len(x_all)):   
        if y_all[i] == current:       
            data.append(x_all[i])
            
    km =  KMeans(n_clusters=nb_clusters, random_state=0).fit(data)
    centroids = km.cluster_centers_
labels = km.labels_


percentages = []
total = len(labels)
for i in range(nb_clusters):
    count = labels.tolist().count(i)
    percentages.append(round(((count/total)*100)))
percentages

    

[42, 22, 12, 23]